import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.scss'
import Head from 'next/head'
import { FavoritesProvider } from './context/FavoritesContext'
import { Navbar } from './components/Navbar'

const poppins = Poppins({
  weight: ['200', '300', '400', '500', '600'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Movie App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <Head>
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <body className={poppins.className}>
        <FavoritesProvider>
          <Navbar />
          <div className='container'>{children}</div>
        </FavoritesProvider>
      </body>
    </html>
  )
}
